/**
 * compileValidationService — deterministic post-compile validation (master prompt §5 + §12).
 *
 * Takes a *compiled* template payload and answers a single question: is this artifact safe
 * and complete enough to proceed downstream? It runs a fixed checklist of quality gates and
 * returns a PASS/BLOCKED verdict plus the list of gate names that blocked.
 *
 * Pure and dependency-free by design. It deliberately does NOT import promptCompilationService
 * (to avoid a module cycle) — it only types the fields it reads off the compiled payload.
 *
 * The §5 separation rule is the load-bearing safety check: an Earthly-Branch hanzi must never
 * be confused with its zodiac-animal hanzi (the canonical example being 申 ↔ 猴). Gate 3
 * (branch_vs_animal_separation) FAILs on such a swap.
 *
 * RED-ON-REVERT: weakening gate 3 to always-PASS breaks the "(b) … 申 with animal 申" test in
 * server/tests/compileValidation.test.ts — that is the proof this validator detects a real defect.
 */

// Validation/gate/result types live in the shared compile contract so the server validator
// and the UI panel (CompileResultPanel) cannot drift apart. Imported for local use AND
// re-exported here so existing importers of this module keep working.
import type {
  GateStatus,
  GateResult,
  Verdict,
  ValidationResult,
  CompiledForValidation,
} from "../../src/lib/compile/compileContract";
export type {
  GateStatus,
  GateResult,
  Verdict,
  ValidationResult,
  CompiledForValidation,
} from "../../src/lib/compile/compileContract";

const REQUIRED_REGION_POLICY = "CN_SIMPLIFIED";
const SOURCE_NEEDED_SENTINEL = "SOURCE_NEEDED";
const LICHUN_UNVERIFIED = "API_VERIFIED_REQUIRED";
const NO_READABLE_HANZI_CLAUSE = "no readable Hanzi generated by the image model";

/**
 * §5 branch ↔ animal pairs that must NEVER be swapped. Keyed both directions so a value in
 * the wrong slot is caught regardless of orientation. The canonical case is 申 (Shen, branch)
 * vs 猴 (Hou, Monkey) — "never replace 申 with 猴 / 猴 with 申". A branch hanzi that equals its
 * own animal hanzi is, by definition, a collapsed/swapped pair.
 */

/** Phrases that instruct the image model to render readable text — forbidden by §12 image policy. */
const READABLE_TEXT_INSTRUCTIONS = [
  "render the hanzi",
  "readable hanzi",
  "readable text",
  "readable pinyin",
  "render the pinyin",
  "render the date",
  "readable date",
  "render the label",
  "readable label",
  "legible text",
  "spell out",
  "write the characters",
];

/** Fate/health/wealth/love/career claim words — forbidden in any user-facing copy or prompt. */
const CLAIM_WORDS = [
  "fate",
  "destiny",
  "fortune",
  "wealth",
  "rich",
  "cure",
  "cures",
  "heal",
  "heals",
  "health",
  "guarantee",
  "guarantees",
  "guaranteed",
  "love",
  "career",
];

const UNRESOLVED_PLACEHOLDER = /\{\{.*?\}\}/;

function check(gate: string, required: string, ok: boolean): GateResult {
  return { gate, required, status: ok ? "PASS" : "FAIL" };
}

/** Escape a string for safe literal use inside a RegExp. */
function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Whole-word / bounded-phrase match (case-insensitive). Word boundaries so a claim word like
 * "love" or "career" does NOT false-positive inside a longer word ("glove", "careers") — a
 * plain substring match would. Multi-word phrases ("render the hanzi") are matched as a
 * bounded unit too.
 */
function containsAny(haystack: string, needles: readonly string[]): boolean {
  return needles.some((n) => new RegExp(`\\b${escapeRegExp(n)}\\b`, "i").test(haystack));
}

/**
 * Validate a compiled payload against the §5 + §12 quality gates.
 *
 * @param input - the compiled template payload (only the read fields are typed)
 * @returns the per-gate results, an overall verdict, and the names of the gates that blocked
 */
export function validateCompiled(input: CompiledForValidation): ValidationResult {
  const placeholderValues = Object.values(input.templatePlaceholders ?? {});
  const sourceStatus = input.sourceStatus ?? {};
  const gates: GateResult[] = [];

  // Gate 1 — region_policy: must be CN_SIMPLIFIED.
  gates.push(
    check(
      "region_policy",
      `regionPolicy === "${REQUIRED_REGION_POLICY}"`,
      input.regionPolicy === REQUIRED_REGION_POLICY,
    ),
  );

  // Gate 2 — no_unresolved_placeholder: no remaining {{...}} in any placeholder value.
  gates.push(
    check(
      "no_unresolved_placeholder",
      "no {{...}} remains in any templatePlaceholders value",
      !placeholderValues.some((v) => UNRESOLVED_PLACEHOLDER.test(v)),
    ),
  );

  // Gate 3 — branch_vs_animal_separation (§5): the branch hanzi must NOT equal the animal hanzi.
  // A collapsed pair (branch === animal) is exactly the 申/猴 swap the rule forbids.
  const branch = input.yearBranchHanzi;
  const animal = input.yearAnimalHanzi;
  const separationOk =
    branch === undefined || animal === undefined || branch !== animal;
  gates.push(
    check(
      "branch_vs_animal_separation",
      "Earthly-Branch hanzi must not equal the zodiac-animal hanzi (§5)",
      separationOk,
    ),
  );

  // Gate 4 — no_unknown_symbols: no sourceStatus value === SOURCE_NEEDED.
  gates.push(
    check(
      "no_unknown_symbols",
      `no sourceStatus value === "${SOURCE_NEEDED_SENTINEL}"`,
      !Object.values(sourceStatus).includes(SOURCE_NEEDED_SENTINEL),
    ),
  );

  // Gate 5 — lichun_provenance: lichun must be present and verified (not API_VERIFIED_REQUIRED).
  const lichun = sourceStatus.lichun;
  gates.push(
    check(
      "lichun_provenance",
      `sourceStatus.lichun present and !== "${LICHUN_UNVERIFIED}"`,
      lichun !== undefined && lichun !== LICHUN_UNVERIFIED,
    ),
  );

  // Gate 6 — image_text_policy: prompt must not request readable text; negatives must carry the clause.
  const promptOk =
    input.imageGenerationPrompt === undefined ||
    !containsAny(input.imageGenerationPrompt, READABLE_TEXT_INSTRUCTIONS);
  const negativesOk =
    input.negativeConstraints === undefined ||
    input.negativeConstraints
      .toLowerCase()
      .includes(NO_READABLE_HANZI_CLAUSE.toLowerCase());
  gates.push(
    check(
      "image_text_policy",
      "image prompt must not render readable Hanzi/Pinyin/labels/dates; negatives include the no-readable-Hanzi clause",
      promptOk && negativesOk,
    ),
  );

  // Gate 7 — claim_safety: no claim words in the image prompt or any placeholder value.
  const claimSurfaces = [...placeholderValues];
  if (input.imageGenerationPrompt !== undefined) {
    claimSurfaces.push(input.imageGenerationPrompt);
  }
  const claimSafe = !claimSurfaces.some((s) => containsAny(s, CLAIM_WORDS));
  gates.push(
    check(
      "claim_safety",
      "no fate/health/wealth/love/career claim words in prompt or placeholder values",
      claimSafe,
    ),
  );

  const blockers = gates.filter((g) => g.status === "FAIL").map((g) => g.gate);
  const verdict: Verdict = blockers.length > 0 ? "BLOCKED" : "PASS";

  return { gates, verdict, blockers };
}
