/**
 * Registry of the BaZi Year-Pillar poster template variants.
 *
 * Data-only: each entry is a frozen template definition the image-generation lane
 * reads (a prose seed, a structured visual direction, the fixed §10 negative
 * constraints, and the placeholder keys the renderer substitutes). The registry
 * itself has no behaviour beyond lookup.
 *
 * Lookup is fail-closed: an unknown id returns an explicit BLOCKED sentinel rather
 * than `undefined`, so a caller cannot silently treat "template not found" as
 * "proceed without a template".
 */

export type RegionPolicy = "CN_SIMPLIFIED";

export type TemplateVariantId =
  | "BEIJING_MODERN_MAINLAND"
  | "SICHUAN_CLASSICAL_MAINLAND";

export interface VisualDirection {
  composition: string;
  materialLanguage: string[];
  motifs: string[];
  mood: string;
}

export interface TemplateDefinition {
  id: string;
  variantId: TemplateVariantId;
  regionPolicy: RegionPolicy;
  /** Seed prose for the LLM prose lane. */
  imageGenerationPromptSeed: string;
  visualDirection: VisualDirection;
  /** The fixed §10 negative-constraint string (shared by all variants). */
  negativeConstraints: string;
  /** Names of the {{...}} placeholders the renderer substitutes. */
  placeholderKeys: string[];
}

/** Returned by getTemplate when the requested id is not registered. */
export interface BlockedTemplateResult {
  status: "BLOCKED";
  reason: "UNKNOWN_TEMPLATE";
}

/** Shared §10 negative constraints — identical across every variant. */
const NEGATIVE_CONSTRAINTS =
  "no fake Chinese, no random Chinese symbols, no fantasy seal, no unreadable calligraphy, no wonton font, no chop suey font, no Asian-looking letters, no Japanese kana, no Korean hangul, no watermark, no mockup, no readable Hanzi generated by the image model, no Pinyin generated by the image model, no labels generated by the image model, no dates generated by the image model, no BaZi table generated by the image model, no deterministic fate claims, no health claims, no wealth claims, no love claims, no career guarantee";

/** Shared placeholder keys — identical across every variant. */
const PLACEHOLDER_KEYS: string[] = [
  "{{year_pillar_hanzi}}",
  "{{year_pillar_pinyin}}",
  "{{year_stem_hanzi}}",
  "{{year_stem_pinyin}}",
  "{{year_branch_hanzi}}",
  "{{year_branch_pinyin}}",
  "{{year_animal_hanzi}}",
  "{{year_animal_pinyin}}",
  "{{year_element_hanzi}}",
  "{{year_element_pinyin}}",
  "{{year_pillar_label_hanzi}}",
  "{{year_pillar_label_pinyin}}",
];

const BEIJING_MODERN: TemplateDefinition = {
  id: "bazi_solo_beijing_modern_v1",
  variantId: "BEIJING_MODERN_MAINLAND",
  regionPolicy: "CN_SIMPLIFIED",
  imageGenerationPromptSeed:
    "Create a premium personalized BaZi Year Pillar poster background in a Beijing Modern Mainland visual direction. Generate a clean, architectural, modern Mainland Chinese composition with calm symmetry, spacious margins, subtle imperial-axis geometry, refined stone-paper texture, restrained ink-wash atmosphere, and a dignified central blank Year Pillar zone. Include a subtle non-textual monkey motif as visual ornament only. The monkey motif must not replace the Earthly Branch. Do not generate readable Chinese characters, Pinyin, labels, names, dates, numbers, tables, seals, or provenance text inside the image.",
  visualDirection: {
    composition: "centered, axial, architectural, calm, modern",
    materialLanguage: ["stone paper", "soft ink wash", "quiet mineral texture"],
    motifs: [
      "abstract Beijing axis",
      "subtle courtyard geometry",
      "non-textual monkey ornament",
    ],
    mood: "precise, restrained, premium, modern Mainland",
  },
  negativeConstraints: NEGATIVE_CONSTRAINTS,
  placeholderKeys: PLACEHOLDER_KEYS,
};

const SICHUAN_CLASSICAL: TemplateDefinition = {
  id: "bazi_solo_sichuan_classical_v1",
  variantId: "SICHUAN_CLASSICAL_MAINLAND",
  regionPolicy: "CN_SIMPLIFIED",
  imageGenerationPromptSeed:
    "Create a premium personalized BaZi Year Pillar poster background in a Sichuan Classical Mainland visual direction. Generate a warm, grounded, atmospheric Mainland Chinese composition inspired by Sichuan mountain mist, tea-house calm, bamboo texture, mineral earth, soft river fog, and carved-paper quietness. Keep the design refined and not folkloric. Include a subtle non-textual monkey motif as visual ornament only. The monkey motif must not replace the Earthly Branch. Do not generate readable Chinese characters, Pinyin, labels, names, dates, numbers, tables, seals, or provenance text inside the image.",
  visualDirection: {
    composition: "warm, layered, misted, grounded, classical-mainland",
    materialLanguage: [
      "bamboo fiber",
      "tea-stained paper",
      "soft mineral earth",
      "river mist",
    ],
    motifs: [
      "Sichuan mountain atmosphere",
      "quiet bamboo rhythm",
      "non-textual monkey ornament",
    ],
    mood: "earthy, calm, poetic, refined, Mainland Chinese",
  },
  negativeConstraints: NEGATIVE_CONSTRAINTS,
  placeholderKeys: PLACEHOLDER_KEYS,
};

const TEMPLATES: Record<string, TemplateDefinition> = {
  [BEIJING_MODERN.id]: BEIJING_MODERN,
  [SICHUAN_CLASSICAL.id]: SICHUAN_CLASSICAL,
};

/**
 * Look up a template by id.
 * @returns the template definition, or a BLOCKED/UNKNOWN_TEMPLATE sentinel.
 */
export function getTemplate(
  id: string
): TemplateDefinition | BlockedTemplateResult {
  const template = TEMPLATES[id];
  if (!template) {
    return { status: "BLOCKED", reason: "UNKNOWN_TEMPLATE" };
  }
  return template;
}

/** List the ids of all registered templates. */
export function listTemplates(): string[] {
  return Object.keys(TEMPLATES);
}
