/**
 * Bazzi Middleware Platform
 * Operational & Visual Quality Issue Taxonomy
 */

export type IssueCategory =
  | 'TEXT'
  | 'LAYOUT'
  | 'STYLE'
  | 'REFERENCE_MATCH'
  | 'PERSONALIZATION'
  | 'SYMBOL_MATCH'
  | 'PRINT_TECHNICAL'
  | 'PROVIDER_GATEWAY'
  | 'QA_MODEL'
  | 'POD_DISPATCH'
  | 'SECURITY'
  | 'DATA_VALIDATION';

export type IssueCode =
  | 'NAME_MISMATCH'
  | 'BIRTH_YEAR_MISMATCH'
  | 'ANIMAL_MISMATCH'
  | 'ELEMENT_MISMATCH'
  | 'TEXT_TOO_CLOSE_TO_EDGE'
  | 'IMAGE_OFF_CENTER'
  | 'REFERENCE_STYLE_DEVIATION'
  | 'EXTRA_TEXT_HALLUCINATION'
  | 'WATERMARK_DETECTED'
  | 'MOCKUP_DETECTED'
  | 'LOW_CONTRAST'
  | 'INVALID_QA_JSON'
  | 'GENERATION_TIMEOUT'
  | 'GENERATION_RATE_LIMIT'
  | 'QA_PROVIDER_TIMEOUT'
  | 'STORAGE_UPLOAD_FAILED'
  | 'POD_PAYLOAD_REJECTED';

export interface QualityIssue {
  id: string;
  category: IssueCategory;
  code: IssueCode;
  severity: 'low' | 'medium' | 'high' | 'critical';
  message: string;
  artifactId?: string;
  createdAt: string;
}

export interface GatewayIssue {
  id: string;
  category: 'PROVIDER_GATEWAY' | 'SECURITY' | 'DATA_VALIDATION';
  code: IssueCode;
  providerId: string;
  errorMessage: string;
  retryAttempt: number;
  createdAt: string;
}

export const ISSUE_CATEGORIES: Record<IssueCategory, string> = {
  TEXT: 'Text Rendering & Font Anomalies',
  LAYOUT: 'Composition & Geometric Spacing',
  STYLE: 'Esthetic & Artistic Direction Adherence',
  REFERENCE_MATCH: 'Reference Style Variance Errors',
  PERSONALIZATION: 'Zodiac & Element Text Alignments',
  SYMBOL_MATCH: 'Mandala & Orbit Vector Graphic Sanity',
  PRINT_TECHNICAL: 'Bleed, DPI & Edge Border Print Margins',
  PROVIDER_GATEWAY: 'Upstream API Gateway / Delivery Fails',
  QA_MODEL: 'VQA scoring engine / Parse Failures',
  POD_DISPATCH: 'Print-on-Demand Payload Rejections',
  SECURITY: 'Secret Key / RBAC Violations',
  DATA_VALIDATION: 'Malformed Astro Client Input Parameters'
};

export const ISSUE_CODES: Record<IssueCode, { category: IssueCategory; description: string }> = {
  NAME_MISMATCH: { category: 'PERSONALIZATION', description: 'Name printed ignores or mismatches requested parameter' },
  BIRTH_YEAR_MISMATCH: { category: 'PERSONALIZATION', description: 'Calendar year printed mismatches astrosophical map details' },
  ANIMAL_MISMATCH: { category: 'PERSONALIZATION', description: 'Animal soul guardian printed is incorrect for specified birth hour' },
  ELEMENT_MISMATCH: { category: 'PERSONALIZATION', description: 'Calculated zodiac element text misspelled or misaligned' },
  TEXT_TOO_CLOSE_TO_EDGE: { category: 'PRINT_TECHNICAL', description: 'Risk of graphic typography loss within physical blade bleed margin' },
  IMAGE_OFF_CENTER: { category: 'LAYOUT', description: 'Graphic canvas core is asymmetric or lacks balancing centering ratios' },
  REFERENCE_STYLE_DEVIATION: { category: 'STYLE', description: 'Generated art deviated from reference mood, contrast or starry layout' },
  EXTRA_TEXT_HALLUCINATION: { category: 'TEXT', description: 'Upstream generator hallucinated random words or copyright taglines' },
  WATERMARK_DETECTED: { category: 'STYLE', description: 'Presence of digital stamps, copyright signs, or sample overlay traces' },
  MOCKUP_DETECTED: { category: 'LAYOUT', description: 'Generator placed vector artwork inside physical smart mockups or picture frames' },
  LOW_CONTRAST: { category: 'PRINT_TECHNICAL', description: 'Foil contrast ratio too low for gold-metallic print foil machines' },
  INVALID_QA_JSON: { category: 'QA_MODEL', description: 'Upstream LLM screening output was malformed JSON or failed model execution schema' },
  GENERATION_TIMEOUT: { category: 'PROVIDER_GATEWAY', description: 'Upstream image engine did not return payload in timeout bounds' },
  GENERATION_RATE_LIMIT: { category: 'PROVIDER_GATEWAY', description: 'API rate limits triggered, stopping live variant swarm creation' },
  QA_PROVIDER_TIMEOUT: { category: 'PROVIDER_GATEWAY', description: 'Vision LLM evaluator offline or failed during token completion' },
  STORAGE_UPLOAD_FAILED: { category: 'PROVIDER_GATEWAY', description: 'Network failed to transmit generated bytes to target Cloud bucket' },
  POD_PAYLOAD_REJECTED: { category: 'POD_DISPATCH', description: 'Gelato payload failed structural formatting validation checks' }
};
