import { describe, it, expect } from "vitest";

/**
 * compileValidationService — deterministic post-compile validation (master prompt §5 + §12).
 *
 * Validates a compiled template payload and returns per-gate quality results plus an
 * overall verdict. The gates encode the §12 quality checklist and the §5 separation rule:
 *   1. region_policy                — must be "CN_SIMPLIFIED".
 *   2. no_unresolved_placeholder    — no remaining {{...}} in any placeholder VALUE.
 *   3. branch_vs_animal_separation  — the Earthly-Branch hanzi must NOT equal the
 *                                     zodiac-animal hanzi (and vice versa). §5: "Never
 *                                     replace 申 with 猴 / 猴 with 申".
 *   4. no_unknown_symbols           — no sourceStatus value === "SOURCE_NEEDED".
 *   5. lichun_provenance            — lichun provenance must be verified (not
 *                                     "API_VERIFIED_REQUIRED", and present).
 *   6. image_text_policy            — the image prompt must not instruct the model to render
 *                                     readable Hanzi/Pinyin/labels/dates, and the negative
 *                                     constraints must include the no-readable-Hanzi clause.
 *   7. claim_safety                 — no fate/health/wealth/love/career claim words in the
 *                                     image prompt or any placeholder value.
 *
 * verdict = "BLOCKED" if ANY gate FAILs (those gate names collected in blockers), else "PASS".
 *
 * RED-ON-REVERT NOTE: weakening gate 3 (branch_vs_animal_separation) to always-PASS — e.g.
 * returning status:"PASS" unconditionally for that gate — MUST break test (b) below
 * ("branch hanzi 申 with animal hanzi 申 → branch_vs_animal_separation FAIL"). That is the
 * proof this validator can go RED on a real swap defect.
 */

import { validateCompiled } from "../services/compileValidationService";

// A valid, fully-resolved 庚午 (Geng-Wu) payload: region OK, lichun verified, clean prose.
function validInput() {
  return {
    variantId: "tee-wuxing-v1",
    regionPolicy: "CN_SIMPLIFIED",
    templatePlaceholders: {
      year_stem_hanzi: "庚",
      year_branch_hanzi: "午",
      year_animal_hanzi: "马",
      tagline: "Born under the year of the Horse.",
    },
    imageGenerationPrompt:
      "A serene watercolor horse galloping through misty mountains, soft palette, no text.",
    negativeConstraints:
      "no readable Hanzi generated by the image model, no watermark, no extra limbs",
    sourceStatus: {
      lichun: "API_VERIFIED",
      year_stem: "MAPPED",
      year_branch: "MAPPED",
    },
    yearBranchHanzi: "午",
    yearAnimalHanzi: "马",
  };
}

function gate(result: ReturnType<typeof validateCompiled>, name: string) {
  return result.gates.find((g) => g.gate === name);
}

describe("validateCompiled — post-compile quality gates (§5 + §12)", () => {
  it("PASSes a valid 庚午 payload with verified lichun and clean prose", () => {
    const result = validateCompiled(validInput());

    expect(result.verdict).toBe("PASS");
    expect(result.blockers).toEqual([]);
    // every gate present and PASS
    for (const g of result.gates) {
      expect(g.status).toBe("PASS");
    }
    // the seven named gates are all present
    const names = result.gates.map((g) => g.gate).sort();
    expect(names).toEqual(
      [
        "branch_vs_animal_separation",
        "claim_safety",
        "image_text_policy",
        "lichun_provenance",
        "no_unknown_symbols",
        "no_unresolved_placeholder",
        "region_policy",
      ].sort(),
    );
  });

  it("BLOCKs when region policy is not CN_SIMPLIFIED (gate region_policy FAIL)", () => {
    const input = validInput();
    input.regionPolicy = "INTL_LATIN";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "region_policy")?.status).toBe("FAIL");
    expect(result.blockers).toContain("region_policy");
  });

  it("(a) BLOCKs when an unresolved {{placeholder}} remains in a value (no_unresolved_placeholder FAIL)", () => {
    const input = validInput();
    input.templatePlaceholders.tagline = "Stem is {{year_stem_hanzi}} this year.";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "no_unresolved_placeholder")?.status).toBe("FAIL");
    expect(result.blockers).toContain("no_unresolved_placeholder");
  });

  it("(b) BLOCKs on a branch/animal swap — branch hanzi 申 with animal hanzi also 申 (branch_vs_animal_separation FAIL)", () => {
    const input = validInput();
    // §5 violation: 申 (Shen, the branch) sitting where the animal 猴 belongs — a swap.
    input.yearBranchHanzi = "申";
    input.yearAnimalHanzi = "申";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "branch_vs_animal_separation")?.status).toBe("FAIL");
    expect(result.blockers).toContain("branch_vs_animal_separation");
  });

  it("(c) BLOCKs when sourceStatus contains a SOURCE_NEEDED (no_unknown_symbols FAIL)", () => {
    const input = validInput();
    input.sourceStatus.year_branch = "SOURCE_NEEDED";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "no_unknown_symbols")?.status).toBe("FAIL");
    expect(result.blockers).toContain("no_unknown_symbols");
  });

  it("(d) BLOCKs when lichun provenance is unverified (API_VERIFIED_REQUIRED → lichun_provenance FAIL)", () => {
    const input = validInput();
    input.sourceStatus.lichun = "API_VERIFIED_REQUIRED";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "lichun_provenance")?.status).toBe("FAIL");
    expect(result.blockers).toContain("lichun_provenance");
  });

  it("(d2) BLOCKs when lichun provenance is missing entirely (lichun_provenance FAIL)", () => {
    const input = validInput();
    delete (input.sourceStatus as Record<string, string>).lichun;

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "lichun_provenance")?.status).toBe("FAIL");
    expect(result.blockers).toContain("lichun_provenance");
  });

  it("(e) BLOCKs when the image prompt instructs rendering readable Hanzi (image_text_policy FAIL)", () => {
    const input = validInput();
    input.imageGenerationPrompt = "A horse scene; render the Hanzi 庚 as readable text on a banner.";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "image_text_policy")?.status).toBe("FAIL");
    expect(result.blockers).toContain("image_text_policy");
  });

  it("(e2) BLOCKs when negativeConstraints omit the no-readable-Hanzi clause (image_text_policy FAIL)", () => {
    const input = validInput();
    input.negativeConstraints = "no watermark, no extra limbs";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "image_text_policy")?.status).toBe("FAIL");
    expect(result.blockers).toContain("image_text_policy");
  });

  it("(f) BLOCKs when a claim word appears (e.g. 'guarantees wealth' → claim_safety FAIL)", () => {
    const input = validInput();
    input.templatePlaceholders.tagline = "This design guarantees wealth and good fortune.";

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(gate(result, "claim_safety")?.status).toBe("FAIL");
    expect(result.blockers).toContain("claim_safety");
  });

  it("collects MULTIPLE failing gate names in blockers when several gates FAIL", () => {
    const input = validInput();
    input.regionPolicy = "INTL_LATIN"; // region_policy
    input.templatePlaceholders.tagline = "guarantees wealth {{leftover}}"; // claim_safety + no_unresolved_placeholder

    const result = validateCompiled(input);

    expect(result.verdict).toBe("BLOCKED");
    expect(result.blockers).toContain("region_policy");
    expect(result.blockers).toContain("claim_safety");
    expect(result.blockers).toContain("no_unresolved_placeholder");
  });
});
