import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';

/**
 * RED CONTRACT — REQ-LGQ-008a / P1 (the real OpenRouter providers are WIRED-IN-PROD:
 * ≥1 production (non-test) importer reachable from the createApp() composition root).
 * Slice A · feat/sizhu-live-generate-qa-loop · TDD Phase 1 (written before impl).
 *
 * Contract surface (T-LGQ-6/7/8, PRD §7; CLAUDE.md P1):
 *   - The real providers exist:
 *       src/lib/providers/openrouter/openRouterImageGenerationProvider.ts
 *       src/lib/providers/openrouter/openRouterQualityGateProvider.ts
 *   - At least one PRODUCTION (non-test, non-smoke) module imports each, and that
 *     module is reachable from server/index.ts (createApp) via the new
 *     POST /api/workflows/:id/run path (e.g. a server run service).
 *
 * Kritische semantische Glättung — REQ-LGQ-008a (BOUNDARY: a built primitive vs a
 * wired one — the exact CLAUDE.md P1 trap):
 *   These:      "The real OpenRouter providers exist and their unit tests pass."
 *   Gegenthese: They are a BUILT-BUT-DEAD primitive — zero production importers; the
 *               run path still constructs Mock providers (or no run path exists).
 *               Every provider unit test is green, yet no real image is EVER
 *               generated by the running server. This is precisely the FuFire-
 *               interpreter "wired-in-prod=yes with zero importers" defect CLAUDE.md
 *               P1 was written to stop. User value = 0.
 *   Schärfung:  Static-trace the import edge: a non-test prod module imports each
 *               real provider, AND the createApp composition root (server/index.ts)
 *               transitively reaches that module on the run path. A grep that finds
 *               the symbol ONLY in tests/smoke fails this contract.
 *
 * VCHK (Vision value-check): triggering a run on the real server actually produces a
 *   real OpenRouter image — the capability is alive, not shelfware.
 *
 * Evidence class: pure-source-grep for the import edge (the runtime proof that an
 *   image is really produced end-to-end is owned by the T-LGQ-9 live smoke).
 *
 * EXPECTED NOW: RED — the provider modules + their production importer do not exist yet.
 */

const ROOT = process.cwd();

const IMAGE_PROVIDER = 'src/lib/providers/openrouter/openRouterImageGenerationProvider.ts';
const QA_PROVIDER = 'src/lib/providers/openrouter/openRouterQualityGateProvider.ts';
const IMAGE_SYMBOL = 'OpenRouterImageGenerationProvider';
const QA_SYMBOL = 'OpenRouterQualityGateProvider';

/** Collect .ts/.tsx files under a dir, excluding tests and smoke (PROD code only). */
function collectProdSources(dirs: string[]): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    if (!existsSync(dir)) return;
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const rel = relative(ROOT, full);
      if (statSync(full).isDirectory()) {
        if (entry === 'node_modules' || entry === 'tests' || entry === '__tests__') continue;
        walk(full);
        continue;
      }
      if (!/\.(ts|tsx)$/.test(entry)) continue;
      if (/\.test\.(ts|tsx)$/.test(entry)) continue; // exclude test files
      if (rel.startsWith('scripts/smoke')) continue; // exclude smoke harness (not prod path)
      out.push(full);
    }
  };
  dirs.forEach(walk);
  return out;
}

function prodImportersOf(symbol: string): string[] {
  const sources = collectProdSources([join(ROOT, 'src'), join(ROOT, 'server')]);
  const importers: string[] = [];
  for (const file of sources) {
    const rel = relative(ROOT, file);
    if (rel === IMAGE_PROVIDER || rel === QA_PROVIDER) continue; // the def itself is not an importer
    const src = readFileSync(file, 'utf8');
    // An import edge: references the symbol AND imports from the openrouter provider path.
    if (src.includes(symbol) && /openRouter(Image|Quality)/.test(src) && /import|require/.test(src)) {
      importers.push(rel);
    }
  }
  return importers;
}

describe('REQ-LGQ-008a — the real OpenRouter provider modules exist', () => {
  it('the image-generation provider module exists and exports its class', () => {
    const p = join(ROOT, IMAGE_PROVIDER);
    expect(existsSync(p)).toBe(true);
    expect(readFileSync(p, 'utf8')).toMatch(new RegExp(`class\\s+${IMAGE_SYMBOL}`));
  });

  it('the quality-gate provider module exists and exports its class', () => {
    const p = join(ROOT, QA_PROVIDER);
    expect(existsSync(p)).toBe(true);
    expect(readFileSync(p, 'utf8')).toMatch(new RegExp(`class\\s+${QA_SYMBOL}`));
  });
});

describe('REQ-LGQ-008a / P1 — each real provider has >=1 PRODUCTION (non-test) importer', () => {
  it('the image provider is imported by at least one prod module (not only tests/smoke)', () => {
    const importers = prodImportersOf(IMAGE_SYMBOL);
    expect(importers.length).toBeGreaterThanOrEqual(1);
    // Mutation RED: leave the provider unimported by prod (dead primitive) → 0 importers.
  });

  it('the QA provider is imported by at least one prod module (not only tests/smoke)', () => {
    const importers = prodImportersOf(QA_SYMBOL);
    expect(importers.length).toBeGreaterThanOrEqual(1);
  });
});

describe('REQ-LGQ-008a / P1 — the importer is reachable from the createApp composition root', () => {
  it('server/index.ts (createApp) transitively reaches a module that imports the real providers', () => {
    // Walk the static import graph from server/index.ts and require that SOME reached
    // prod module imports a real OpenRouter provider. This is the composition-root
    // reachability proof: built + imported-somewhere is NOT enough; it must be on the
    // server boot path (the run endpoint lives in createApp).
    const reached = new Set<string>();
    const queue: string[] = ['server/index.ts'];

    const resolveImport = (fromRel: string, spec: string): string | null => {
      if (!spec.startsWith('.') && !spec.startsWith('@/')) return null; // skip node_modules
      let base: string;
      if (spec.startsWith('@/')) {
        base = join(ROOT, spec.slice(2));
      } else {
        base = join(ROOT, fromRel, '..', spec);
      }
      const candidates = [
        `${base}.ts`,
        `${base}.tsx`,
        join(base, 'index.ts'),
        join(base, 'index.tsx'),
      ];
      for (const c of candidates) {
        if (existsSync(c)) return relative(ROOT, c);
      }
      return null;
    };

    while (queue.length) {
      const rel = queue.shift()!;
      if (reached.has(rel)) continue;
      reached.add(rel);
      const full = join(ROOT, rel);
      if (!existsSync(full)) continue;
      const src = readFileSync(full, 'utf8');
      const importRe = /(?:import[^'"]*|require\()\s*['"]([^'"]+)['"]/g;
      let m: RegExpExecArray | null;
      while ((m = importRe.exec(src))) {
        const resolved = resolveImport(rel, m[1]);
        if (resolved && !resolved.includes('/tests/') && !resolved.includes('scripts/smoke')) {
          queue.push(resolved);
        }
      }
    }

    const reachesRealProvider = [...reached].some((rel) => {
      if (rel === IMAGE_PROVIDER || rel === QA_PROVIDER) return true;
      const src = readFileSync(join(ROOT, rel), 'utf8');
      return /openRouter(Image|Quality)/.test(src) && (src.includes(IMAGE_SYMBOL) || src.includes(QA_SYMBOL));
    });

    expect(reachesRealProvider).toBe(true);
    // Mutation RED: wire the run endpoint to Mock* providers instead of the real
    // ones → createApp never reaches the real provider module → RED. Proves the
    // run path is composed with the REAL providers, not green-on-mocks.
  });
});
