import { describe, it, expect } from "vitest";
import {
  getTemplate,
  listTemplates,
} from "../services/templateRegistryService";

/**
 * RED CONTRACT — BaZi Year-Pillar poster template registry.
 *
 * Two CN_SIMPLIFIED variants (Beijing Modern, Sichuan Classical) are data-only
 * definitions looked up by id. An unknown id MUST return an explicit BLOCKED
 * sentinel — never a silent undefined that a caller could treat as "no template,
 * proceed anyway".
 */
describe("templateRegistryService", () => {
  it("returns the Beijing Modern template with the correct region policy + variant", () => {
    const tpl = getTemplate("bazi_solo_beijing_modern_v1");
    expect(tpl).not.toHaveProperty("status");
    if ("status" in tpl) throw new Error("expected a template definition");
    expect(tpl.regionPolicy).toBe("CN_SIMPLIFIED");
    expect(tpl.variantId).toBe("BEIJING_MODERN_MAINLAND");
  });

  it("returns the Sichuan Classical template", () => {
    const tpl = getTemplate("bazi_solo_sichuan_classical_v1");
    expect(tpl).not.toHaveProperty("status");
    if ("status" in tpl) throw new Error("expected a template definition");
    expect(tpl.variantId).toBe("SICHUAN_CLASSICAL_MAINLAND");
    expect(tpl.regionPolicy).toBe("CN_SIMPLIFIED");
  });

  it("returns a BLOCKED/UNKNOWN_TEMPLATE sentinel for an unknown id", () => {
    const result = getTemplate("nope");
    expect(result).toEqual({
      status: "BLOCKED",
      reason: "UNKNOWN_TEMPLATE",
    });
  });

  it("lists both template ids", () => {
    const ids = listTemplates();
    expect(ids).toContain("bazi_solo_beijing_modern_v1");
    expect(ids).toContain("bazi_solo_sichuan_classical_v1");
    expect(ids).toHaveLength(2);
  });

  it("carries the fixed negative constraints including the no-readable-Hanzi rule", () => {
    const tpl = getTemplate("bazi_solo_beijing_modern_v1");
    if ("status" in tpl) throw new Error("expected a template definition");
    expect(tpl.negativeConstraints).toContain(
      "no readable Hanzi generated by the image model"
    );
  });
});
